config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :articles
    resources :blog_categories do
      resources :blogs
    end
    resources :orders
    resources :products do
      resources :stocks
    end
      resources :categories
  end
  devise_for :admins
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"

  authenticated :admin_user do
    root to: "admin#index", as: :admin_root
  end

  resources :categories, only: [:show, :index]
  resources :products, only: [:show, :index]
  resources :blog_categories, only: [:index, :show]
  resources :blogs, only: [:show]
  resources :carts, only: [:create, :show, :destroy] do
    collection do
      post 'update_quantity'
    end
  end

  get "admin" => "admin#index"
  # get "cart" => "carts#show"
  post "checkout" => "checkouts#create"
  get "success" => "checkouts#success"
  get "cancel" => "checkouts#cancel"
  post "webhooks" => "webhooks#stripe"
end

app/models/blog_category.rb
class BlogCategory < ApplicationRecord
  has_one_attached :image do |attachable|
    attachable.variant :thumb, resize_to_limit: [50, 50]
  end

  has_many :blogs
end

app/controllers/admin/blog_categories_controller.rb
class Admin::BlogCategoriesController < AdminController
  layout 'admin'
  before_action :set_admin_blog_category, only: %i[ show edit update destroy ]

  # GET /admin/categories or /admin/categories.json
  def index
    @admin_blog_categories = BlogCategory.all
  end

  # GET /admin/categories/1 or /admin/categories/1.json
  def show
  end

  # GET /admin/categories/new
  def new
    @admin_blog_category = BlogCategory.new
  end

  # GET /admin/categories/1/edit
  def edit
  end

  # POST /admin/categories or /admin/categories.json
  def create
    @admin_blog_category = BlogCategory.new(admin_blog_category_params)

    respond_to do |format|
      if @admin_blog_category.save
        format.html { redirect_to admin_blog_category_url(@admin_blog_category), notice: "Blog Category was successfully created." }
        format.json { render :show, status: :created, location: @admin_blog_category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @admin_blog_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/categories/1 or /admin/categories/1.json
  def update
    respond_to do |format|
      if @admin_blog_category.update(admin_blog_category_params)
        format.html { redirect_to admin_blog_category_url(@admin_blog_category), notice: "Blog Category was successfully updated." }
        format.json { render :show, status: :ok, location: @admin_blog_category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @admin_blog_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/categories/1 or /admin/categories/1.json
  def destroy
    @admin_blog_category.destroy!

    respond_to do |format|
      format.html { redirect_to admin_blog_categories_url, notice: "Blog Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_blog_category
      @admin_blog_category = BlogCategory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def admin_blog_category_params
      params.require(:blog_category).permit(:name, :description, :image)
    end
end

app/controllers/blog_categories_controller.rb
class BlogCategoriesController < ApplicationController
  def index
    @blog_categories = BlogCategory.all
  end

  def show
    @blog_category = BlogCategory.find(params[:id])
    @blogs = @blog_category.blogs
  end
end

app/helpers/admin/blog_categories_helper.rb
module Admin::BlogCategoriesHelper
end

app/helpers/blog_categories_helper.rb
module BlogCategoriesHelper
end

app/views/admin/blog_categories/_blog_category.html.erb
<div id="<%= dom_id blog_category %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= blog_category.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= blog_category.description %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this blog category", [:admin, blog_category], class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this blog category", edit_admin_blog_category_path(blog_category), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>

</div>

app/views/admin/blog_categories/_form.html.erb
<%= form_with(model: [:admin, admin_blog_category], class: "contents") do |form| %>
  <% if admin_blog_category.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(admin_blog_category.errors.count, "error") %> prohibited this admin_blog_category from being saved:</h2>

      <ul>
        <% admin_blog_category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: "tinymce block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mb-8 mt-2 w-full" %>
    <%= tinymce %>
  </div>

  <div class="my-5">
    <%= form.label :image %>
    <%= form.file_field :image, rows: 4, class: "block shadow rounded-md border border-sky-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :active %>
    <%= form.check_box :active, class: "block mt-2 h-5 w-5" %>
  </div>

  <% unless admin_blog_category.new_record? %>
    <div class="my-5">
      <%= link_to "Blog Posts", admin_blog_category_blogs_path(admin_blog_category), class: "underline" %>
    </div>
  <% end %>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/admin/blog_categories/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing blog category</h1>

  <%= render "form", admin_blog_category: @admin_blog_category %>

  <%= link_to "Show this blog category", [:admin, @admin_blog_category], class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to blog categories", admin_blog_categories_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/admin/blog_categories/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Blog Categories</h1>
    <%= link_to "New category", new_admin_blog_category_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div class="flex flex-col w-full">
    <div class="overlow-x-auto sm:mx-0.5 lg:mx-0.5">
      <div class="py-2 inline-block min-w-full">
        <div class="overlow-x-auto">
          <table class="min-w-full overflow-x-scroll">
            <thead class="bg-white border-b">
              <tr>
                <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">
                </th>
                <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">
                  Name
                </th>
                <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">
                  Description 
                </th>
              </tr>
            </thead>
            <tbody>
              <% @admin_blog_categories.each do |c| %>
                <tr class="bg-gray-50 border-b">
                  <td class="px-6 py-4 whitepsace-nowrap tex-sm font-medium text-gray-800 underline">
                    <%= c.image.present? ? image_tag(c.image.variant(:thumb)) : image_tag("https://via.placeholder.com/50") %>
                  </td>
                  <td class="px-6 py-4 whitepsace-nowrap tex-sm font-medium text-gray-800 underline">
                    <%= link_to c.name, edit_admin_blog_category_path(c) %>
                  </td>
                  <td class="px-6 py-4 whitepsace-nowrap tex-sm font-medium text-gray-800">
                    <%= c.description %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/blog_categories/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New blog category</h1>

  <%= render "form", admin_blog_category: @admin_blog_category %>

  <%= link_to "Back to blog categories", admin_blog_categories_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/admin/blog_categories/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @admin_blog_category %>

    <%= link_to "Edit this blog category", edit_admin_blog_category_path(@admin_blog_category), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to blog categories", admin_blog_categories_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this blog category", admin_blog_category_path(@admin_blog_category), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>