config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :articles
    resources :blog_categories do
      resources :blogs
    end
    resources :orders
    resources :products do
      resources :stocks
    end
      resources :categories
  end
  devise_for :admins
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"

  authenticated :admin_user do
    root to: "admin#index", as: :admin_root
  end

  resources :categories, only: [:show, :index]
  resources :products, only: [:show, :index]
  resources :blog_categories, only: [:index, :show]
  resources :blogs, only: [:show]
  resources :carts, only: [:create, :show, :destroy] do
    collection do
      post 'update_quantity'
    end
  end

  get "admin" => "admin#index"
  # get "cart" => "carts#show"
  post "checkout" => "checkouts#create"
  get "success" => "checkouts#success"
  get "cancel" => "checkouts#cancel"
  post "webhooks" => "webhooks#stripe"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :blog_category
  has_rich_text :body
  has_one_attached :image

  validates :body, presence: true
end

app/models/blog.rb
class Blog < ApplicationRecord
  has_one_attached :image do |attachable|
    attachable.variant :thumb, resize_to_limit: [50, 50]
  end
  
  belongs_to :blog_category
  has_rich_text :content
end

app/models/blog_category.rb
class BlogCategory < ApplicationRecord
  has_one_attached :image do |attachable|
    attachable.variant :thumb, resize_to_limit: [50, 50]
  end

  has_many :blogs
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :products, through: :cart_items

  before_create :set_secret_id

  enum status: { pending: 0, complete: 1 }

  private

  def set_secret_id
    self.secret_id = SecureRandom.uuid + DateTime.now.to_i.to_s
  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product

  def total_price
    product.price * quantity
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_one_attached :image do |attachable|
    attachable.variant :thumb, resize_to_limit: [50, 50]
  end

  has_many :products, dependent: :destroy
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_products
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
  has_many_attached :images do |attachable|
    attachable.variant :thumb, resize_to_limit: [50, 50]
    attachable.variant :medium, resize_to_limit: [250, 250]
  end

  belongs_to :category
  has_many :stocks
  has_many :order_products
  has_many :cart_items
end

app/models/product_stock.rb
class ProductStock < ApplicationRecord
  belongs_to :product
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :product
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout 'admin'
  before_action :authenticate_admin!

  def index
    @orders = Order.where(fulfilled: false).order(created_at: :desc).take(5)
    @quick_stats = { 
      sales: Order.where(created_at: Time.now.midnight..Time.now).count,
      revenue: Order.where(created_at: Time.now.midnight..Time.now).sum(:total)&.round(),
      avg_sale: Order.where(created_at: Time.now.midnight..Time.now).average(:total)&.round(),
      per_sale: OrderProduct.joins(:order).where(orders: { created_at: Time.now.midnight..Time.now })&.average(:quantity)
    }
    @orders_by_day = Order.where('created_at > ?', Time.now - 7.days).order(:created_at)
    @orders_by_day = @orders_by_day.group_by { |order| order.created_at.to_date }
    @revenue_by_day = @orders_by_day.map { |day, orders| [day.strftime("%A"), orders.sum(&:total)] }
    if @revenue_by_day.count < 7
      days_of_week = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]

      data_hash = @revenue_by_day.to_h
      current_day = Date.today.strftime("%A")
      current_day_index = days_of_week.index(current_day)
      next_day_index = (current_day_index + 1) % days_of_week.length

      ordered_days_with_current_last = days_of_week[next_day_index..-1] + days_of_week[0...next_day_index]

      complete_ordered_array_with_current_last = ordered_days_with_current_last.map{ |day| [day, data_hash.fetch(day, 0)] }

      @revenue_by_day = complete_ordered_array_with_current_last 
    end
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def show
    @blog = Blog.find(params[:id])
    @blogs = Blog.where(blog_category_id: @blog.blog_category_id)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_product, only: [:create, :destroy]
  protect_from_forgery with: :exception
  def create
    @current_cart.cart_items.create(product_id: @product.id)
  end

  def show
  end

  def checkout
  end

  def destroy
    @cart_item = @current_cart.cart_items.find_by_product_id(@product.id)
    @cart_item.destroy
    redirect_to cart_path(@current_cart)
  end

  def success
    if @current_cart.cart_items.any?
      session[:current_cart_id] = nil
    end
    @purchased_cart = Cart.find_by_secret_id(params[:id])
    redirect_to root_path if !@purchased_cart
  end

  def update_quantity
    @cart = Cart.find_by(secret_id: params[:secret_id])
    product = Product.find(params[:product_id])
    cart_item = @cart.cart_items.find_by(product: product)
    cart_item.update(quantity: params[:quantity])

    total_price = cart_item.quantity * product.price
    subtotal = @cart.cart_items.sum { |item| item.quantity * item.product.price }

    render json: { total_price: total_price, subtotal: subtotal }
  end

  private

  def current_cart
    Cart.find_by(secret_id: session[:cart_secret_id])
  end

  def set_product
    @product = Product.find(params[:product_id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @desktop_carousel_images = ["image1.jpg", "image2.jpg", "image3.jpg"]
    @mobile_carousel_images = ["mobile_image1.jpg", "mobile_image2.jpg", "mobile_image3.jpg"]
    @main_products = Product.take(6)
    @main_categories = Category.take(4)
    @main_blog_categories = BlogCategory.take(4)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/blog_categories_helper.rb
module BlogCategoriesHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/admin/index.html.erb
<h1>Admin Home</h1>

<div>
    <h2 class="text-2xl text-sky-800 font-medium mb-4">Daily Stats</h2>
  <div class="flex gap-10 flex-col md:flex-row justify-between w-full">
    <div class="max-w-sm rounded overflow-hidden shadow-xl bg-gradient-to-r from-sky-400 to-sky-300">
      <div class="px-6 py-4">
        <div class="font-bold text-xl mb-2 text-white">Revenue</div>
        <p class="text-white text-base">
          Ksh <%= @quick_stats[:revenue] ? (@quick_stats[:revenue]).to_s : "0" %>
        </p>
      </div>
    </div>
    <div class="max-w-sm rounded overflow-hidden shadow-xl bg-gradient-to-r from-sky-400 to-sky-300">
      <div class="px-6 py-4">
        <div class="font-bold text-xl mb-2 text-white">Total Sales</div>
        <p class="text-white text-base">
          <%= @quick_stats[:sales] ? (@quick_stats[:sales]).to_s : "0" %>
        </p>
      </div>
    </div>
    <div class="max-w-sm rounded overflow-hidden shadow-xl bg-gradient-to-r from-sky-400 to-sky-300">
      <div class="px-6 py-4">
        <div class="font-bold text-xl mb-2 text-white">Average Sale</div>
        <p class="text-white text-base">
          Ksh <%= @quick_stats[:avg_sale] ? (@quick_stats[:avg_sale]).to_s : "0" %>
        </p>
      </div>
    </div>
    <div class="max-w-sm rounded overflow-hidden shadow-xl bg-gradient-to-r from-sky-400 to-sky-300">
      <div class="px-6 py-4">
        <div class="font-bold text-xl mb-2 text-white">Items/Sale</div>
        <p class="text-white text-base">
          <%= @quick_stats[:per_sale].to_i %>
        </p>
      </div>
    </div>
  </div>

  <div class="my-8 w-full">
    <h2 class="text-2xl text-sky-800 font-medium mb-4">Revenue</h2>
    <div class="w-full" data-controller="dashboard" data-dashboard-revenue-value="<%= @revenue_by_day.to_json %>">
      <canvas id="revenueChart"></canvas>
    </div>
  </div>

  <div class="flex flex-col w-full">
    <h2 class="text-2xl text-sky-800 mb-4 font-medium">Recent Unfulfilled Orders</h2>
    <div class="overflow-x-auto">
      <table class="min-w-full bg-sky-100" style="border-collapse: separate; border-spacing: 0;">
      <thead>
        <tr class="text-sky-800">
          <th class="px-6 py-3 border-b-2 border-sky-200 bg-sky-100">Order ID</th>
          <th class="px-6 py-3 border-b-2 border-sky-200 bg-sky-100">Customer</th>
          <th class="px-6 py-3 border-b-2 border-sky-200 bg-sky-100">Date</th>
          <th class="px-6 py-3 border-b-2 border-sky-200 bg-sky-100">Amount</th>
        </tr>
      </thead>
      <tbody class="text-sky-700">
        <% @orders.each do |order| %>
          <tr>
            <td class="px-6 py-4 border-b border-sky-200">
              <%= link_to order.id, admin_order_path(order), class: "underline" %>
            </td>
            <td class="px-6 py-4 border-b border-sky-200">
              <%= order.customer_email %>
            </td>
            <td class="px-6 py-4 border-b border-sky-200">
              <%= order.created_at.strftime("%B %d, %Y %H:%M") %>
            </td>
            <td class="px-6 py-4 border-b border-sky-200">
              <%= (order.total).to_s %>
            </td>
          </tr>
        <% end %>
      </tbody>
      </table>
    </div>
  </div>

</div>

app/views/shared/_footer.html.erb
<footer class="bg-sky-800 text-white py-6 sm:py-8">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <div class="grid grid-cols-1 md:grid-cols-3 gap-8">
        <!-- About Section -->
        <div class="space-y-4">
          <h3 class="text-sm font-semibold uppercase">About Gems of Insight</h3>
          <p class="text-sm">Gems of Insight is a leading online marketplace, offering a wide range of quality products to cater to all your needs.</p>
        </div>

        <!-- Contact Information -->
        <div class="space-y-4">
          <h3 class="text-sm font-semibold uppercase">Contact</h3>
          <ul class="text-sm space-y-2">
            <li>HQ: Nairobi, 12345</li>
            <li>Email: info@gemsofinsight.com</li>
            <li>Phone: +254795029654</li>
          </ul>
        </div>
      </div>
      <!-- Copyright Notice -->
      <div class="border-t border-sky-700 mt-6 pt-6">
        <p class="text-xs text-sky-400 text-center">&copy; <%= Time.now.year %> Gems of Insight. All rights reserved.</p>
      </div>
    </div>
  </footer>

app/views/shared/_navbar.html.erb
<nav class="w-full h-23 pt-4 pb-4 top-0 bg-white shadow z-10">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="flex items-center justify-between h-16">
      <div class="flex items-center">
        <%= link_to root_path do %>
          <%= image_tag 'logo.png', class: 'h-auto w-64' %>
        <% end %>
      </div>
      <div class="hidden md:block">
        <div class="ml-10 flex items-baseline space-x-4">
          <%= link_to 'Home', root_path, class: "text-sky-500 hover:text-sky-900 px-3 py-2 rounded-md text-xl font-medium text-decoration-none" %>
          <%= link_to 'Shop', categories_path, class: "text-sky-500 hover:text-sky-900 px-3 py-2 rounded-md text-xl font-medium text-decoration-none" %>
          <%= link_to 'Blogs', blog_categories_path, class: "text-sky-500 hover:text-sky-900 px-3 py-2 rounded-md text-xl font-medium text-decoration-none" %>
          <%= link_to 'Products', products_path, class: "text-sky-500 hover:text-sky-900 px-3 py-2 rounded-md text-xl font-medium text-decoration-none" %>
          <%= link_to cart_path(@current_cart&.secret_id), class: "text-sky-500 hover:text-sky-900 focus:outline-none relative flex items-center" do %>
            <i class="fas fa-shopping-cart text-3xl"></i> <!-- Adjust icon size here -->
            <% if @current_cart&.cart_items&.any? %>
              <div class="bg-sky-500 px-2 py-1 mb-6 text-xs text-grey-100 rounded-full">
                <%= @current_cart.cart_items.count %>
              </div>
            <% end %>
          <% end %>
      </div>
      </div>
      <div class="relative md:hidden flex items-center">
        <%= link_to cart_path(@current_cart&.secret_id), class: "text-sky-500 hover:text-sky-900 focus:outline-none relative flex items-center" do %>
          <i class="fas fa-shopping-cart text-3xl"></i> <!-- Adjust icon size here -->
          <% if @current_cart&.cart_items&.any? %>
            <div class="bg-sky-500 px-2 py-1 mb-6 text-xs text-grey-100 rounded-full">
              <%= @current_cart.cart_items.count %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</nav>

<!-- Sticky Bottom Navbar for Mobile -->
<div class="fixed bottom-0 left-0 right-0 w-full bg-white shadow z-10 md:hidden tab-bar">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="flex justify-between py-2">
      <%= link_to root_path, class: "text-sky-500 hover:text-sky-900 flex flex-col items-center" do %>
        <i class="fas fa-home"></i>
        <span class="text-xs">Home</span>
      <% end %>
      <%= link_to categories_path, class: "text-sky-500 hover:text-sky-900 flex flex-col items-center" do %>
        <i class="fas fa-list"></i>
        <span class="text-xs">Categories</span>
      <% end %>
      <%= link_to products_path, class: "text-sky-500 hover:text-sky-900 flex flex-col items-center" do %>
        <i class="fas fa-box-open"></i>
        <span class="text-xs">Products</span>
      <% end %>
      <%= link_to blog_categories_path, class: "text-sky-500 hover:text-sky-900 flex flex-col items-center" do %>
        <i class="fas fa-blog"></i>
        <span class="text-xs">Blogs</span>
      <% end %>
    </div>
  </div>
</div>

<!-- WhatsApp and Back to Top Buttons -->
<div class="fixed bottom-0 left-0 right-0 w-full bg-none flex justify-between px-4 py-2 z-20 md:hidden mb-12">
  <a href="whatsapp://send?phone=+254795029654" class="bg-green-500 text-white p-3 rounded-full hover:bg-green-600 transition duration-300">
    <i class="fab fa-whatsapp"></i>
  </a>
  <a href="#" id="back-to-top" class="bg-gray-500 text-white p-3 rounded-full hover:bg-gray-600 transition duration-300">
    <i class="fas fa-arrow-up"></i>
  </a>
</div>


<script>
  // Back to top functionality
  document.getElementById('back-to-top').addEventListener('click', function(e) {
    e.preventDefault();
    window.scrollTo({ top: 0, behavior: 'smooth' });
  });

  document.addEventListener('DOMContentLoaded', () => {
    const tabBar = document.querySelector('.tab-bar');
    const observer = new IntersectionObserver((entries) => {
        entries.forEach(entry => {
            if (entry.intersectionRatio < 1) {
                tabBar.classList.add('tab-bar-hidden');
            } else {
                tabBar.classList.remove('tab-bar-hidden');
            }
        });
    }, { threshold: [1] });

    observer.observe(document.querySelector('.cart-container'));
  });
</script>